//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALOJAMIENTO
    {
        public System.DateTime INGRESO { get; set; }
        public Nullable<System.DateTime> EGRESO { get; set; }
        public Nullable<short> REGISTRO_DIAS { get; set; }
        public string OBSERVACIONES { get; set; }
        public string CONFIRMADO { get; set; }
        public string RUT_PERSONA { get; set; }
        public decimal CODIGO_CAMA { get; set; }
        public decimal NUMERO_OC { get; set; }
    
        public virtual CAMA CAMA { get; set; }
        public virtual ORDEN_DE_COMPRA ORDEN_DE_COMPRA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
