//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.DIRECCION = new HashSet<DIRECCION>();
        }
    
        public string NOMBRE { get; set; }
        public short COD_AREA { get; set; }
        public short COD_PAIS { get; set; }
    
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<DIRECCION> DIRECCION { get; set; }
    }
}
