//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public string CALLE { get; set; }
        public int NUMERO { get; set; }
        public string COMUNA { get; set; }
        public string COD_POSTAL { get; set; }
        public string NOMBRE_CIUDAD { get; set; }
        public Nullable<short> COD_PAIS { get; set; }
        public string RUT_PERSONA { get; set; }
        public string RUT_EMPRESA { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
