//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public string TIPO { get; set; }
        public decimal NUMERO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int VALOR_BRUTO { get; set; }
        public int VALOR_IVA { get; set; }
        public int VALOR_NETO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string UBICACION { get; set; }
        public Nullable<decimal> NUMERO_OC { get; set; }
        public Nullable<decimal> NUMERO_OP { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ORDEN_DE_COMPRA ORDEN_DE_COMPRA { get; set; }
        public virtual ORDEN_DE_PEDIDO ORDEN_DE_PEDIDO { get; set; }
        public virtual PAGO PAGO { get; set; }
    }
}
