//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        public HABITACION()
        {
            this.CAMA = new HashSet<CAMA>();
        }
    
        public short CODIGO { get; set; }
        public string ESTADO { get; set; }
        public short CAPACIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public int PRECIO { get; set; }
    
        public virtual ICollection<CAMA> CAMA { get; set; }
    }
}
