//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DE_PEDIDO
    {
        public ORDEN_DE_PEDIDO()
        {
            this.FACTURA = new HashSet<FACTURA>();
            this.RRP = new HashSet<RRP>();
        }
    
        public decimal NUMERO { get; set; }
        public System.DateTime EMISION { get; set; }
        public int MONTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string UBICACION { get; set; }
        public string ESTADO { get; set; }
        public string RUT_PROVEEDOR { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<RRP> RRP { get; set; }
    }
}
