//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DE_COMPRA
    {
        public ORDEN_DE_COMPRA()
        {
            this.COMIDA = new HashSet<COMIDA>();
            this.FACTURA = new HashSet<FACTURA>();
            this.ALOJAMIENTO = new HashSet<ALOJAMIENTO>();
        }
    
        public decimal NUMERO { get; set; }
        public System.DateTime RECEPCION { get; set; }
        public int MONTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string UBICACION { get; set; }
        public string ESTADO { get; set; }
        public string RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<COMIDA> COMIDA { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<ALOJAMIENTO> ALOJAMIENTO { get; set; }
    }
}
