//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public string TIPO_FACTURA { get; set; }
        public decimal NUMERO_FACTURA { get; set; }
        public string MEDIO_PAGO { get; set; }
        public string DIVISA { get; set; }
        public string CODIGO_ISO { get; set; }
        public string MONTO { get; set; }
        public Nullable<decimal> TASA_CAMBIO_CLP { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
