//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.RRP = new HashSet<RRP>();
        }
    
        public short CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public int PRECIO { get; set; }
        public short STOCK { get; set; }
        public short STOCK_CRITICO { get; set; }
    
        public virtual ICollection<RRP> RRP { get; set; }
    }
}
