//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.ORDEN_DE_PEDIDO = new HashSet<ORDEN_DE_PEDIDO>();
            this.PROVISION = new HashSet<PROVISION>();
        }
    
        public string RUT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<ORDEN_DE_PEDIDO> ORDEN_DE_PEDIDO { get; set; }
        public virtual ICollection<PROVISION> PROVISION { get; set; }
    }
}
