//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRP
    {
        public long CODIGO { get; set; }
        public short INDICE { get; set; }
        public System.DateTime RECEPCION { get; set; }
        public string CONFIRMADO { get; set; }
        public short CODIGO_PRODUCTO { get; set; }
        public decimal NUMERO_OP { get; set; }
    
        public virtual ORDEN_DE_PEDIDO ORDEN_DE_PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
