//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public string PERFIL { get; set; }
        public string ESTADO { get; set; }
        public string RUT_PERSONA { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
