//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWSPresentacion.WSSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSoap.IWSSHostel")]
    public interface IWSSHostel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ValidarLogin", ReplyAction="http://tempuri.org/IWSSHostel/ValidarLoginResponse")]
        CapaObjeto.Sesion ValidarLogin(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ValidarLogin", ReplyAction="http://tempuri.org/IWSSHostel/ValidarLoginResponse")]
        System.Threading.Tasks.Task<CapaObjeto.Sesion> ValidarLoginAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/UsuarioRescatar", ReplyAction="http://tempuri.org/IWSSHostel/UsuarioRescatarResponse")]
        CapaObjeto.ContenedorUsuarios UsuarioRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/UsuarioRescatar", ReplyAction="http://tempuri.org/IWSSHostel/UsuarioRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorUsuarios> UsuarioRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteCrearResponse")]
        CapaObjeto.ContenedorPerfilUsuarioCliente PerfilUsuarioClienteCrear(CapaObjeto.ContenedorPerfilUsuarioCliente entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioCliente> PerfilUsuarioClienteCrearAsync(CapaObjeto.ContenedorPerfilUsuarioCliente entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteActualizarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioCliente PerfilUsuarioClienteActualizar(CapaObjeto.ContenedorPerfilUsuarioCliente entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioCliente> PerfilUsuarioClienteActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioCliente entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteRescatarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioClientes PerfilUsuarioClienteRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioClientes> PerfilUsuarioClienteRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteBuscarPorRut", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteBuscarPorRutResponse")]
        CapaObjeto.PerfilUsuarioCliente PerfilUsuarioClienteBuscarPorRut(string rut, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteBuscarPorRut", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioClienteBuscarPorRutResponse")]
        System.Threading.Tasks.Task<CapaObjeto.PerfilUsuarioCliente> PerfilUsuarioClienteBuscarPorRutAsync(string rut, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorCrearResponse")]
        CapaObjeto.ContenedorPerfilUsuarioProveedor PerfilUsuarioProveedorCrear(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioProveedor> PerfilUsuarioProveedorCrearAsync(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorActualizarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioProveedor PerfilUsuarioProveedorActualizar(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioProveedor> PerfilUsuarioProveedorActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorRescatarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioProveedores PerfilUsuarioProveedorRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioProveedores> PerfilUsuarioProveedorRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorBuscarPorRut", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorBuscarPorRutResponse")]
        CapaObjeto.PerfilUsuarioProveedor PerfilUsuarioProveedorBuscarPorRut(string rut, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorBuscarPorRut", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioProveedorBuscarPorRutResponse")]
        System.Threading.Tasks.Task<CapaObjeto.PerfilUsuarioProveedor> PerfilUsuarioProveedorBuscarPorRutAsync(string rut, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoCrearResponse")]
        CapaObjeto.ContenedorPerfilUsuarioEmpleado PerfilUsuarioEmpleadoCrear(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioEmpleado> PerfilUsuarioEmpleadoCrearAsync(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoActualizarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioEmpleado PerfilUsuarioEmpleadoActualizar(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioEmpleado> PerfilUsuarioEmpleadoActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoRescatarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioEmpleados PerfilUsuarioEmpleadoRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioEmpleadoRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioEmpleados> PerfilUsuarioEmpleadoRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorCrearResponse")]
        CapaObjeto.ContenedorPerfilUsuarioAdministrador PerfilUsuarioAdministradorCrear(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorCrear", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioAdministrador> PerfilUsuarioAdministradorCrearAsync(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorActualizarResponse")]
        CapaObjeto.ContenedorPerfilUsuarioAdministrador PerfilUsuarioAdministradorActualizar(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioAdministrador> PerfilUsuarioAdministradorActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorEliminar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorEliminarResponse")]
        bool PerfilUsuarioAdministradorEliminar(CapaObjeto.ContenedorPerfilUsuarioAdministrador nPUA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorEliminar", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorEliminarResponse")]
        System.Threading.Tasks.Task<bool> PerfilUsuarioAdministradorEliminarAsync(CapaObjeto.ContenedorPerfilUsuarioAdministrador nPUA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorBuscarPorRut", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorBuscarPorRutResponse")]
        CapaObjeto.PerfilUsuarioAdministrador PerfilUsuarioAdministradorBuscarPorRut(string rut, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorBuscarPorRut", ReplyAction="http://tempuri.org/IWSSHostel/PerfilUsuarioAdministradorBuscarPorRutResponse")]
        System.Threading.Tasks.Task<CapaObjeto.PerfilUsuarioAdministrador> PerfilUsuarioAdministradorBuscarPorRutAsync(string rut, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoCrear", ReplyAction="http://tempuri.org/IWSSHostel/ProductoCrearResponse")]
        CapaObjeto.ContenedorProducto ProductoCrear(CapaObjeto.ContenedorProducto entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoCrear", ReplyAction="http://tempuri.org/IWSSHostel/ProductoCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProducto> ProductoCrearAsync(CapaObjeto.ContenedorProducto entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoActualizar", ReplyAction="http://tempuri.org/IWSSHostel/ProductoActualizarResponse")]
        CapaObjeto.ContenedorProducto ProductoActualizar(CapaObjeto.ContenedorProducto entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoActualizar", ReplyAction="http://tempuri.org/IWSSHostel/ProductoActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProducto> ProductoActualizarAsync(CapaObjeto.ContenedorProducto entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoEliminar", ReplyAction="http://tempuri.org/IWSSHostel/ProductoEliminarResponse")]
        CapaObjeto.ContenedorProducto ProductoEliminar(CapaObjeto.ContenedorProducto entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoEliminar", ReplyAction="http://tempuri.org/IWSSHostel/ProductoEliminarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProducto> ProductoEliminarAsync(CapaObjeto.ContenedorProducto entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ProductoRescatarResponse")]
        CapaObjeto.ContenedorProductos ProductoRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProductoRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ProductoRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProductos> ProductoRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ServicioComidaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ServicioComidaRescatarResponse")]
        CapaObjeto.ContenedorServiciosComida ServicioComidaRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ServicioComidaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ServicioComidaRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorServiciosComida> ServicioComidaRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoCrear", ReplyAction="http://tempuri.org/IWSSHostel/PlatoCrearResponse")]
        CapaObjeto.ContenedorPlato PlatoCrear(CapaObjeto.ContenedorPlato entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoCrear", ReplyAction="http://tempuri.org/IWSSHostel/PlatoCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPlato> PlatoCrearAsync(CapaObjeto.ContenedorPlato entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PlatoActualizarResponse")]
        CapaObjeto.ContenedorPlato PlatoActualizar(CapaObjeto.ContenedorPlato entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoActualizar", ReplyAction="http://tempuri.org/IWSSHostel/PlatoActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPlato> PlatoActualizarAsync(CapaObjeto.ContenedorPlato entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoEliminar", ReplyAction="http://tempuri.org/IWSSHostel/PlatoEliminarResponse")]
        CapaObjeto.ContenedorPlato PlatoEliminar(CapaObjeto.ContenedorPlato entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoEliminar", ReplyAction="http://tempuri.org/IWSSHostel/PlatoEliminarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPlato> PlatoEliminarAsync(CapaObjeto.ContenedorPlato entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PlatoRescatarResponse")]
        CapaObjeto.ContenedorPlatos PlatoRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PlatoRescatar", ReplyAction="http://tempuri.org/IWSSHostel/PlatoRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorPlatos> PlatoRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionCrear", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionCrearResponse")]
        CapaObjeto.ContenedorHabitacion HabitacionCrear(CapaObjeto.ContenedorHabitacion entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionCrear", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitacion> HabitacionCrearAsync(CapaObjeto.ContenedorHabitacion entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionActualizar", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionActualizarResponse")]
        CapaObjeto.ContenedorHabitacion HabitacionActualizar(CapaObjeto.ContenedorHabitacion entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionActualizar", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitacion> HabitacionActualizarAsync(CapaObjeto.ContenedorHabitacion entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionEliminar", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionEliminarResponse")]
        CapaObjeto.ContenedorHabitacion HabitacionEliminar(CapaObjeto.ContenedorHabitacion entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionEliminar", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionEliminarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitacion> HabitacionEliminarAsync(CapaObjeto.ContenedorHabitacion entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionRescatar", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionRescatarResponse")]
        CapaObjeto.ContenedorHabitaciones HabitacionRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionRescatar", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitaciones> HabitacionRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionHabXCapacidad", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionHabXCapacidadResponse")]
        CapaObjeto.ContenedorHabDispCant HabitacionHabXCapacidad(string token, System.DateTime fecIng, System.DateTime fecEgr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/HabitacionHabXCapacidad", ReplyAction="http://tempuri.org/IWSSHostel/HabitacionHabXCapacidadResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorHabDispCant> HabitacionHabXCapacidadAsync(string token, System.DateTime fecIng, System.DateTime fecEgr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CiudadRescatar", ReplyAction="http://tempuri.org/IWSSHostel/CiudadRescatarResponse")]
        CapaObjeto.ContenedorCiudades CiudadRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CiudadRescatar", ReplyAction="http://tempuri.org/IWSSHostel/CiudadRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorCiudades> CiudadRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaCrear", ReplyAction="http://tempuri.org/IWSSHostel/CamaCrearResponse")]
        CapaObjeto.ContenedorCama CamaCrear(CapaObjeto.ContenedorCama entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaCrear", ReplyAction="http://tempuri.org/IWSSHostel/CamaCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorCama> CamaCrearAsync(CapaObjeto.ContenedorCama entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaActualizar", ReplyAction="http://tempuri.org/IWSSHostel/CamaActualizarResponse")]
        CapaObjeto.ContenedorCama CamaActualizar(CapaObjeto.ContenedorCama entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaActualizar", ReplyAction="http://tempuri.org/IWSSHostel/CamaActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorCama> CamaActualizarAsync(CapaObjeto.ContenedorCama entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaEliminar", ReplyAction="http://tempuri.org/IWSSHostel/CamaEliminarResponse")]
        CapaObjeto.ContenedorCama CamaEliminar(CapaObjeto.ContenedorCama entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaEliminar", ReplyAction="http://tempuri.org/IWSSHostel/CamaEliminarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorCama> CamaEliminarAsync(CapaObjeto.ContenedorCama entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/CamaRescatarResponse")]
        CapaObjeto.ContenedorCamas CamaRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/CamaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/CamaRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorCamas> CamaRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenCompraCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/OrdenCompraCompletaCrearResponse")]
        CapaObjeto.ContenedorOrdenCompraCompleta OrdenCompraCompletaCrear(CapaObjeto.ContenedorOrdenCompraCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenCompraCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/OrdenCompraCompletaCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenCompraCompleta> OrdenCompraCompletaCrearAsync(CapaObjeto.ContenedorOrdenCompraCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenCompraCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/OrdenCompraCompletaRescatarResponse")]
        CapaObjeto.ContenedorOrdenesCompraCompleta OrdenCompraCompletaRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenCompraCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/OrdenCompraCompletaRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenesCompraCompleta> OrdenCompraCompletaRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/AlojConfirHueActualizar", ReplyAction="http://tempuri.org/IWSSHostel/AlojConfirHueActualizarResponse")]
        CapaObjeto.ContenedorAlojamiento AlojConfirHueActualizar(CapaObjeto.ContenedorAlojamiento entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/AlojConfirHueActualizar", ReplyAction="http://tempuri.org/IWSSHostel/AlojConfirHueActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorAlojamiento> AlojConfirHueActualizarAsync(CapaObjeto.ContenedorAlojamiento entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaCrearResponse")]
        CapaObjeto.ContenedorOrdenPedidoCompleta OrdenPedidoCompletaCrear(CapaObjeto.ContenedorOrdenPedidoCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenPedidoCompleta> OrdenPedidoCompletaCrearAsync(CapaObjeto.ContenedorOrdenPedidoCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaRescatarResponse")]
        CapaObjeto.ContenedorOrdenesPedidoCompleta OrdenPedidoCompletaRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/OrdenPedidoCompletaRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenesPedidoCompleta> OrdenPedidoCompletaRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProdConfirRecepActualizar", ReplyAction="http://tempuri.org/IWSSHostel/ProdConfirRecepActualizarResponse")]
        CapaObjeto.ContenedorRegistroRecepcionPedido ProdConfirRecepActualizar(CapaObjeto.ContenedorRegistroRecepcionPedido entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProdConfirRecepActualizar", ReplyAction="http://tempuri.org/IWSSHostel/ProdConfirRecepActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorRegistroRecepcionPedido> ProdConfirRecepActualizarAsync(CapaObjeto.ContenedorRegistroRecepcionPedido entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaCompraCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/FacturaCompraCompletaCrearResponse")]
        CapaObjeto.ContenedorFacturaCompraCompleta FacturaCompraCompletaCrear(CapaObjeto.ContenedorFacturaCompraCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaCompraCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/FacturaCompraCompletaCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturaCompraCompleta> FacturaCompraCompletaCrearAsync(CapaObjeto.ContenedorFacturaCompraCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaCompraCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/FacturaCompraCompletaRescatarResponse")]
        CapaObjeto.ContenedorFacturasCompraCompleta FacturaCompraCompletaRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaCompraCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/FacturaCompraCompletaRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturasCompraCompleta> FacturaCompraCompletaRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaCrearResponse")]
        CapaObjeto.ContenedorFacturaPedidoCompleta FacturaPedidoCompletaCrear(CapaObjeto.ContenedorFacturaPedidoCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaCrear", ReplyAction="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturaPedidoCompleta> FacturaPedidoCompletaCrearAsync(CapaObjeto.ContenedorFacturaPedidoCompleta entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaRescatarResponse")]
        CapaObjeto.ContenedorFacturasPedidoCompleta FacturaPedidoCompletaRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaRescatar", ReplyAction="http://tempuri.org/IWSSHostel/FacturaPedidoCompletaRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturasPedidoCompleta> FacturaPedidoCompletaRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/StockProductos", ReplyAction="http://tempuri.org/IWSSHostel/StockProductosResponse")]
        CapaObjeto.Producto[] StockProductos(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/StockProductos", ReplyAction="http://tempuri.org/IWSSHostel/StockProductosResponse")]
        System.Threading.Tasks.Task<CapaObjeto.Producto[]> StockProductosAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Productos_mas_solicitados", ReplyAction="http://tempuri.org/IWSSHostel/Productos_mas_solicitadosResponse")]
        CapaObjeto.ComodinJava[] Productos_mas_solicitados(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Productos_mas_solicitados", ReplyAction="http://tempuri.org/IWSSHostel/Productos_mas_solicitadosResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Productos_mas_solicitadosAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Segun_rubro_empresa", ReplyAction="http://tempuri.org/IWSSHostel/Segun_rubro_empresaResponse")]
        CapaObjeto.ComodinJava[] Segun_rubro_empresa(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Segun_rubro_empresa", ReplyAction="http://tempuri.org/IWSSHostel/Segun_rubro_empresaResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Segun_rubro_empresaAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Metodo_pago_mas_usado", ReplyAction="http://tempuri.org/IWSSHostel/Metodo_pago_mas_usadoResponse")]
        CapaObjeto.ComodinJava[] Metodo_pago_mas_usado(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Metodo_pago_mas_usado", ReplyAction="http://tempuri.org/IWSSHostel/Metodo_pago_mas_usadoResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Metodo_pago_mas_usadoAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Ciudad_mas_solicita_servicios", ReplyAction="http://tempuri.org/IWSSHostel/Ciudad_mas_solicita_serviciosResponse")]
        CapaObjeto.ComodinJava[] Ciudad_mas_solicita_servicios(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Ciudad_mas_solicita_servicios", ReplyAction="http://tempuri.org/IWSSHostel/Ciudad_mas_solicita_serviciosResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Ciudad_mas_solicita_serviciosAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Estado_habitaciones", ReplyAction="http://tempuri.org/IWSSHostel/Estado_habitacionesResponse")]
        CapaObjeto.ComodinJava[] Estado_habitaciones(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Estado_habitaciones", ReplyAction="http://tempuri.org/IWSSHostel/Estado_habitacionesResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Estado_habitacionesAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Habitaciones_mas_solicitadas", ReplyAction="http://tempuri.org/IWSSHostel/Habitaciones_mas_solicitadasResponse")]
        CapaObjeto.ComodinJava[] Habitaciones_mas_solicitadas(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Habitaciones_mas_solicitadas", ReplyAction="http://tempuri.org/IWSSHostel/Habitaciones_mas_solicitadasResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Habitaciones_mas_solicitadasAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Fecha_mayor_auge", ReplyAction="http://tempuri.org/IWSSHostel/Fecha_mayor_augeResponse")]
        CapaObjeto.ComodinJava[] Fecha_mayor_auge(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Fecha_mayor_auge", ReplyAction="http://tempuri.org/IWSSHostel/Fecha_mayor_augeResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Fecha_mayor_augeAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/SolicitudesNoTerminadas", ReplyAction="http://tempuri.org/IWSSHostel/SolicitudesNoTerminadasResponse")]
        CapaObjeto.ComodinJava[] SolicitudesNoTerminadas(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/SolicitudesNoTerminadas", ReplyAction="http://tempuri.org/IWSSHostel/SolicitudesNoTerminadasResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> SolicitudesNoTerminadasAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Promedio_venta_mensual", ReplyAction="http://tempuri.org/IWSSHostel/Promedio_venta_mensualResponse")]
        CapaObjeto.ComodinJava[] Promedio_venta_mensual(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/Promedio_venta_mensual", ReplyAction="http://tempuri.org/IWSSHostel/Promedio_venta_mensualResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Promedio_venta_mensualAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PromedioPerdidaMensual", ReplyAction="http://tempuri.org/IWSSHostel/PromedioPerdidaMensualResponse")]
        CapaObjeto.ComodinJava[] PromedioPerdidaMensual(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PromedioPerdidaMensual", ReplyAction="http://tempuri.org/IWSSHostel/PromedioPerdidaMensualResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> PromedioPerdidaMensualAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PorcentageCierreEfectivo", ReplyAction="http://tempuri.org/IWSSHostel/PorcentageCierreEfectivoResponse")]
        CapaObjeto.ComodinJava[] PorcentageCierreEfectivo(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/PorcentageCierreEfectivo", ReplyAction="http://tempuri.org/IWSSHostel/PorcentageCierreEfectivoResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> PorcentageCierreEfectivoAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProveedorRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ProveedorRescatarResponse")]
        CapaObjeto.ContenedorProveedores ProveedorRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProveedorRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ProveedorRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProveedores> ProveedorRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ClienteRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ClienteRescatarResponse")]
        CapaObjeto.ContenedorClientes ClienteRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ClienteRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ClienteRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorClientes> ClienteRescatarAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/listaProveedores", ReplyAction="http://tempuri.org/IWSSHostel/listaProveedoresResponse")]
        string[][] listaProveedores(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/listaProveedores", ReplyAction="http://tempuri.org/IWSSHostel/listaProveedoresResponse")]
        System.Threading.Tasks.Task<string[][]> listaProveedoresAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/listaClientes", ReplyAction="http://tempuri.org/IWSSHostel/listaClientesResponse")]
        string[][] listaClientes(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/listaClientes", ReplyAction="http://tempuri.org/IWSSHostel/listaClientesResponse")]
        System.Threading.Tasks.Task<string[][]> listaClientesAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ListaUsuario", ReplyAction="http://tempuri.org/IWSSHostel/ListaUsuarioResponse")]
        string[][] ListaUsuario(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ListaUsuario", ReplyAction="http://tempuri.org/IWSSHostel/ListaUsuarioResponse")]
        System.Threading.Tasks.Task<string[][]> ListaUsuarioAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionCrear", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionCrearResponse")]
        CapaObjeto.ContenedorProvision ProvisionCrear(CapaObjeto.ContenedorProvision entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionCrear", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionCrearResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProvision> ProvisionCrearAsync(CapaObjeto.ContenedorProvision entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionActualizar", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionActualizarResponse")]
        CapaObjeto.ContenedorProvision ProvisionActualizar(CapaObjeto.ContenedorProvision entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionActualizar", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionActualizarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProvision> ProvisionActualizarAsync(CapaObjeto.ContenedorProvision entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionEliminar", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionEliminarResponse")]
        CapaObjeto.ContenedorProvision ProvisionEliminar(CapaObjeto.ContenedorProvision entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionEliminar", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionEliminarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProvision> ProvisionEliminarAsync(CapaObjeto.ContenedorProvision entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionRescatarResponse")]
        CapaObjeto.ContenedorProvisiones ProvisionRescatar(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSSHostel/ProvisionRescatar", ReplyAction="http://tempuri.org/IWSSHostel/ProvisionRescatarResponse")]
        System.Threading.Tasks.Task<CapaObjeto.ContenedorProvisiones> ProvisionRescatarAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSSHostelChannel : CapaWSPresentacion.WSSoap.IWSSHostel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSHostelClient : System.ServiceModel.ClientBase<CapaWSPresentacion.WSSoap.IWSSHostel>, CapaWSPresentacion.WSSoap.IWSSHostel {
        
        public WSSHostelClient() {
        }
        
        public WSSHostelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSHostelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSHostelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSHostelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaObjeto.Sesion ValidarLogin(string usuario, string clave) {
            return base.Channel.ValidarLogin(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.Sesion> ValidarLoginAsync(string usuario, string clave) {
            return base.Channel.ValidarLoginAsync(usuario, clave);
        }
        
        public CapaObjeto.ContenedorUsuarios UsuarioRescatar(string token) {
            return base.Channel.UsuarioRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorUsuarios> UsuarioRescatarAsync(string token) {
            return base.Channel.UsuarioRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioCliente PerfilUsuarioClienteCrear(CapaObjeto.ContenedorPerfilUsuarioCliente entrada) {
            return base.Channel.PerfilUsuarioClienteCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioCliente> PerfilUsuarioClienteCrearAsync(CapaObjeto.ContenedorPerfilUsuarioCliente entrada) {
            return base.Channel.PerfilUsuarioClienteCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioCliente PerfilUsuarioClienteActualizar(CapaObjeto.ContenedorPerfilUsuarioCliente entrada) {
            return base.Channel.PerfilUsuarioClienteActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioCliente> PerfilUsuarioClienteActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioCliente entrada) {
            return base.Channel.PerfilUsuarioClienteActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioClientes PerfilUsuarioClienteRescatar(string token) {
            return base.Channel.PerfilUsuarioClienteRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioClientes> PerfilUsuarioClienteRescatarAsync(string token) {
            return base.Channel.PerfilUsuarioClienteRescatarAsync(token);
        }
        
        public CapaObjeto.PerfilUsuarioCliente PerfilUsuarioClienteBuscarPorRut(string rut, string token) {
            return base.Channel.PerfilUsuarioClienteBuscarPorRut(rut, token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.PerfilUsuarioCliente> PerfilUsuarioClienteBuscarPorRutAsync(string rut, string token) {
            return base.Channel.PerfilUsuarioClienteBuscarPorRutAsync(rut, token);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioProveedor PerfilUsuarioProveedorCrear(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada) {
            return base.Channel.PerfilUsuarioProveedorCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioProveedor> PerfilUsuarioProveedorCrearAsync(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada) {
            return base.Channel.PerfilUsuarioProveedorCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioProveedor PerfilUsuarioProveedorActualizar(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada) {
            return base.Channel.PerfilUsuarioProveedorActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioProveedor> PerfilUsuarioProveedorActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioProveedor entrada) {
            return base.Channel.PerfilUsuarioProveedorActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioProveedores PerfilUsuarioProveedorRescatar(string token) {
            return base.Channel.PerfilUsuarioProveedorRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioProveedores> PerfilUsuarioProveedorRescatarAsync(string token) {
            return base.Channel.PerfilUsuarioProveedorRescatarAsync(token);
        }
        
        public CapaObjeto.PerfilUsuarioProveedor PerfilUsuarioProveedorBuscarPorRut(string rut, string token) {
            return base.Channel.PerfilUsuarioProveedorBuscarPorRut(rut, token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.PerfilUsuarioProveedor> PerfilUsuarioProveedorBuscarPorRutAsync(string rut, string token) {
            return base.Channel.PerfilUsuarioProveedorBuscarPorRutAsync(rut, token);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioEmpleado PerfilUsuarioEmpleadoCrear(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada) {
            return base.Channel.PerfilUsuarioEmpleadoCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioEmpleado> PerfilUsuarioEmpleadoCrearAsync(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada) {
            return base.Channel.PerfilUsuarioEmpleadoCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioEmpleado PerfilUsuarioEmpleadoActualizar(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada) {
            return base.Channel.PerfilUsuarioEmpleadoActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioEmpleado> PerfilUsuarioEmpleadoActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioEmpleado entrada) {
            return base.Channel.PerfilUsuarioEmpleadoActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioEmpleados PerfilUsuarioEmpleadoRescatar(string token) {
            return base.Channel.PerfilUsuarioEmpleadoRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioEmpleados> PerfilUsuarioEmpleadoRescatarAsync(string token) {
            return base.Channel.PerfilUsuarioEmpleadoRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioAdministrador PerfilUsuarioAdministradorCrear(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada) {
            return base.Channel.PerfilUsuarioAdministradorCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioAdministrador> PerfilUsuarioAdministradorCrearAsync(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada) {
            return base.Channel.PerfilUsuarioAdministradorCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPerfilUsuarioAdministrador PerfilUsuarioAdministradorActualizar(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada) {
            return base.Channel.PerfilUsuarioAdministradorActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPerfilUsuarioAdministrador> PerfilUsuarioAdministradorActualizarAsync(CapaObjeto.ContenedorPerfilUsuarioAdministrador entrada) {
            return base.Channel.PerfilUsuarioAdministradorActualizarAsync(entrada);
        }
        
        public bool PerfilUsuarioAdministradorEliminar(CapaObjeto.ContenedorPerfilUsuarioAdministrador nPUA) {
            return base.Channel.PerfilUsuarioAdministradorEliminar(nPUA);
        }
        
        public System.Threading.Tasks.Task<bool> PerfilUsuarioAdministradorEliminarAsync(CapaObjeto.ContenedorPerfilUsuarioAdministrador nPUA) {
            return base.Channel.PerfilUsuarioAdministradorEliminarAsync(nPUA);
        }
        
        public CapaObjeto.PerfilUsuarioAdministrador PerfilUsuarioAdministradorBuscarPorRut(string rut, string token) {
            return base.Channel.PerfilUsuarioAdministradorBuscarPorRut(rut, token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.PerfilUsuarioAdministrador> PerfilUsuarioAdministradorBuscarPorRutAsync(string rut, string token) {
            return base.Channel.PerfilUsuarioAdministradorBuscarPorRutAsync(rut, token);
        }
        
        public CapaObjeto.ContenedorProducto ProductoCrear(CapaObjeto.ContenedorProducto entrada) {
            return base.Channel.ProductoCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProducto> ProductoCrearAsync(CapaObjeto.ContenedorProducto entrada) {
            return base.Channel.ProductoCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorProducto ProductoActualizar(CapaObjeto.ContenedorProducto entrada) {
            return base.Channel.ProductoActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProducto> ProductoActualizarAsync(CapaObjeto.ContenedorProducto entrada) {
            return base.Channel.ProductoActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorProducto ProductoEliminar(CapaObjeto.ContenedorProducto entrada) {
            return base.Channel.ProductoEliminar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProducto> ProductoEliminarAsync(CapaObjeto.ContenedorProducto entrada) {
            return base.Channel.ProductoEliminarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorProductos ProductoRescatar(string token) {
            return base.Channel.ProductoRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProductos> ProductoRescatarAsync(string token) {
            return base.Channel.ProductoRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorServiciosComida ServicioComidaRescatar(string token) {
            return base.Channel.ServicioComidaRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorServiciosComida> ServicioComidaRescatarAsync(string token) {
            return base.Channel.ServicioComidaRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorPlato PlatoCrear(CapaObjeto.ContenedorPlato entrada) {
            return base.Channel.PlatoCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPlato> PlatoCrearAsync(CapaObjeto.ContenedorPlato entrada) {
            return base.Channel.PlatoCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPlato PlatoActualizar(CapaObjeto.ContenedorPlato entrada) {
            return base.Channel.PlatoActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPlato> PlatoActualizarAsync(CapaObjeto.ContenedorPlato entrada) {
            return base.Channel.PlatoActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPlato PlatoEliminar(CapaObjeto.ContenedorPlato entrada) {
            return base.Channel.PlatoEliminar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPlato> PlatoEliminarAsync(CapaObjeto.ContenedorPlato entrada) {
            return base.Channel.PlatoEliminarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorPlatos PlatoRescatar(string token) {
            return base.Channel.PlatoRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorPlatos> PlatoRescatarAsync(string token) {
            return base.Channel.PlatoRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorHabitacion HabitacionCrear(CapaObjeto.ContenedorHabitacion entrada) {
            return base.Channel.HabitacionCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitacion> HabitacionCrearAsync(CapaObjeto.ContenedorHabitacion entrada) {
            return base.Channel.HabitacionCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorHabitacion HabitacionActualizar(CapaObjeto.ContenedorHabitacion entrada) {
            return base.Channel.HabitacionActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitacion> HabitacionActualizarAsync(CapaObjeto.ContenedorHabitacion entrada) {
            return base.Channel.HabitacionActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorHabitacion HabitacionEliminar(CapaObjeto.ContenedorHabitacion entrada) {
            return base.Channel.HabitacionEliminar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitacion> HabitacionEliminarAsync(CapaObjeto.ContenedorHabitacion entrada) {
            return base.Channel.HabitacionEliminarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorHabitaciones HabitacionRescatar(string token) {
            return base.Channel.HabitacionRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorHabitaciones> HabitacionRescatarAsync(string token) {
            return base.Channel.HabitacionRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorHabDispCant HabitacionHabXCapacidad(string token, System.DateTime fecIng, System.DateTime fecEgr) {
            return base.Channel.HabitacionHabXCapacidad(token, fecIng, fecEgr);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorHabDispCant> HabitacionHabXCapacidadAsync(string token, System.DateTime fecIng, System.DateTime fecEgr) {
            return base.Channel.HabitacionHabXCapacidadAsync(token, fecIng, fecEgr);
        }
        
        public CapaObjeto.ContenedorCiudades CiudadRescatar(string token) {
            return base.Channel.CiudadRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorCiudades> CiudadRescatarAsync(string token) {
            return base.Channel.CiudadRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorCama CamaCrear(CapaObjeto.ContenedorCama entrada) {
            return base.Channel.CamaCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorCama> CamaCrearAsync(CapaObjeto.ContenedorCama entrada) {
            return base.Channel.CamaCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorCama CamaActualizar(CapaObjeto.ContenedorCama entrada) {
            return base.Channel.CamaActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorCama> CamaActualizarAsync(CapaObjeto.ContenedorCama entrada) {
            return base.Channel.CamaActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorCama CamaEliminar(CapaObjeto.ContenedorCama entrada) {
            return base.Channel.CamaEliminar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorCama> CamaEliminarAsync(CapaObjeto.ContenedorCama entrada) {
            return base.Channel.CamaEliminarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorCamas CamaRescatar(string token) {
            return base.Channel.CamaRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorCamas> CamaRescatarAsync(string token) {
            return base.Channel.CamaRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorOrdenCompraCompleta OrdenCompraCompletaCrear(CapaObjeto.ContenedorOrdenCompraCompleta entrada) {
            return base.Channel.OrdenCompraCompletaCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenCompraCompleta> OrdenCompraCompletaCrearAsync(CapaObjeto.ContenedorOrdenCompraCompleta entrada) {
            return base.Channel.OrdenCompraCompletaCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorOrdenesCompraCompleta OrdenCompraCompletaRescatar(string token) {
            return base.Channel.OrdenCompraCompletaRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenesCompraCompleta> OrdenCompraCompletaRescatarAsync(string token) {
            return base.Channel.OrdenCompraCompletaRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorAlojamiento AlojConfirHueActualizar(CapaObjeto.ContenedorAlojamiento entrada) {
            return base.Channel.AlojConfirHueActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorAlojamiento> AlojConfirHueActualizarAsync(CapaObjeto.ContenedorAlojamiento entrada) {
            return base.Channel.AlojConfirHueActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorOrdenPedidoCompleta OrdenPedidoCompletaCrear(CapaObjeto.ContenedorOrdenPedidoCompleta entrada) {
            return base.Channel.OrdenPedidoCompletaCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenPedidoCompleta> OrdenPedidoCompletaCrearAsync(CapaObjeto.ContenedorOrdenPedidoCompleta entrada) {
            return base.Channel.OrdenPedidoCompletaCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorOrdenesPedidoCompleta OrdenPedidoCompletaRescatar(string token) {
            return base.Channel.OrdenPedidoCompletaRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorOrdenesPedidoCompleta> OrdenPedidoCompletaRescatarAsync(string token) {
            return base.Channel.OrdenPedidoCompletaRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorRegistroRecepcionPedido ProdConfirRecepActualizar(CapaObjeto.ContenedorRegistroRecepcionPedido entrada) {
            return base.Channel.ProdConfirRecepActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorRegistroRecepcionPedido> ProdConfirRecepActualizarAsync(CapaObjeto.ContenedorRegistroRecepcionPedido entrada) {
            return base.Channel.ProdConfirRecepActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorFacturaCompraCompleta FacturaCompraCompletaCrear(CapaObjeto.ContenedorFacturaCompraCompleta entrada) {
            return base.Channel.FacturaCompraCompletaCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturaCompraCompleta> FacturaCompraCompletaCrearAsync(CapaObjeto.ContenedorFacturaCompraCompleta entrada) {
            return base.Channel.FacturaCompraCompletaCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorFacturasCompraCompleta FacturaCompraCompletaRescatar(string token) {
            return base.Channel.FacturaCompraCompletaRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturasCompraCompleta> FacturaCompraCompletaRescatarAsync(string token) {
            return base.Channel.FacturaCompraCompletaRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorFacturaPedidoCompleta FacturaPedidoCompletaCrear(CapaObjeto.ContenedorFacturaPedidoCompleta entrada) {
            return base.Channel.FacturaPedidoCompletaCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturaPedidoCompleta> FacturaPedidoCompletaCrearAsync(CapaObjeto.ContenedorFacturaPedidoCompleta entrada) {
            return base.Channel.FacturaPedidoCompletaCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorFacturasPedidoCompleta FacturaPedidoCompletaRescatar(string token) {
            return base.Channel.FacturaPedidoCompletaRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorFacturasPedidoCompleta> FacturaPedidoCompletaRescatarAsync(string token) {
            return base.Channel.FacturaPedidoCompletaRescatarAsync(token);
        }
        
        public CapaObjeto.Producto[] StockProductos(string token) {
            return base.Channel.StockProductos(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.Producto[]> StockProductosAsync(string token) {
            return base.Channel.StockProductosAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Productos_mas_solicitados(string token) {
            return base.Channel.Productos_mas_solicitados(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Productos_mas_solicitadosAsync(string token) {
            return base.Channel.Productos_mas_solicitadosAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Segun_rubro_empresa(string token) {
            return base.Channel.Segun_rubro_empresa(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Segun_rubro_empresaAsync(string token) {
            return base.Channel.Segun_rubro_empresaAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Metodo_pago_mas_usado(string token) {
            return base.Channel.Metodo_pago_mas_usado(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Metodo_pago_mas_usadoAsync(string token) {
            return base.Channel.Metodo_pago_mas_usadoAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Ciudad_mas_solicita_servicios(string token) {
            return base.Channel.Ciudad_mas_solicita_servicios(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Ciudad_mas_solicita_serviciosAsync(string token) {
            return base.Channel.Ciudad_mas_solicita_serviciosAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Estado_habitaciones(string token) {
            return base.Channel.Estado_habitaciones(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Estado_habitacionesAsync(string token) {
            return base.Channel.Estado_habitacionesAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Habitaciones_mas_solicitadas(string token) {
            return base.Channel.Habitaciones_mas_solicitadas(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Habitaciones_mas_solicitadasAsync(string token) {
            return base.Channel.Habitaciones_mas_solicitadasAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Fecha_mayor_auge(string token) {
            return base.Channel.Fecha_mayor_auge(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Fecha_mayor_augeAsync(string token) {
            return base.Channel.Fecha_mayor_augeAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] SolicitudesNoTerminadas(string token) {
            return base.Channel.SolicitudesNoTerminadas(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> SolicitudesNoTerminadasAsync(string token) {
            return base.Channel.SolicitudesNoTerminadasAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] Promedio_venta_mensual(string token) {
            return base.Channel.Promedio_venta_mensual(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> Promedio_venta_mensualAsync(string token) {
            return base.Channel.Promedio_venta_mensualAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] PromedioPerdidaMensual(string token) {
            return base.Channel.PromedioPerdidaMensual(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> PromedioPerdidaMensualAsync(string token) {
            return base.Channel.PromedioPerdidaMensualAsync(token);
        }
        
        public CapaObjeto.ComodinJava[] PorcentageCierreEfectivo(string token) {
            return base.Channel.PorcentageCierreEfectivo(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ComodinJava[]> PorcentageCierreEfectivoAsync(string token) {
            return base.Channel.PorcentageCierreEfectivoAsync(token);
        }
        
        public CapaObjeto.ContenedorProveedores ProveedorRescatar(string token) {
            return base.Channel.ProveedorRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProveedores> ProveedorRescatarAsync(string token) {
            return base.Channel.ProveedorRescatarAsync(token);
        }
        
        public CapaObjeto.ContenedorClientes ClienteRescatar(string token) {
            return base.Channel.ClienteRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorClientes> ClienteRescatarAsync(string token) {
            return base.Channel.ClienteRescatarAsync(token);
        }
        
        public string[][] listaProveedores(string token) {
            return base.Channel.listaProveedores(token);
        }
        
        public System.Threading.Tasks.Task<string[][]> listaProveedoresAsync(string token) {
            return base.Channel.listaProveedoresAsync(token);
        }
        
        public string[][] listaClientes(string token) {
            return base.Channel.listaClientes(token);
        }
        
        public System.Threading.Tasks.Task<string[][]> listaClientesAsync(string token) {
            return base.Channel.listaClientesAsync(token);
        }
        
        public string[][] ListaUsuario(string token) {
            return base.Channel.ListaUsuario(token);
        }
        
        public System.Threading.Tasks.Task<string[][]> ListaUsuarioAsync(string token) {
            return base.Channel.ListaUsuarioAsync(token);
        }
        
        public CapaObjeto.ContenedorProvision ProvisionCrear(CapaObjeto.ContenedorProvision entrada) {
            return base.Channel.ProvisionCrear(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProvision> ProvisionCrearAsync(CapaObjeto.ContenedorProvision entrada) {
            return base.Channel.ProvisionCrearAsync(entrada);
        }
        
        public CapaObjeto.ContenedorProvision ProvisionActualizar(CapaObjeto.ContenedorProvision entrada) {
            return base.Channel.ProvisionActualizar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProvision> ProvisionActualizarAsync(CapaObjeto.ContenedorProvision entrada) {
            return base.Channel.ProvisionActualizarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorProvision ProvisionEliminar(CapaObjeto.ContenedorProvision entrada) {
            return base.Channel.ProvisionEliminar(entrada);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProvision> ProvisionEliminarAsync(CapaObjeto.ContenedorProvision entrada) {
            return base.Channel.ProvisionEliminarAsync(entrada);
        }
        
        public CapaObjeto.ContenedorProvisiones ProvisionRescatar(string token) {
            return base.Channel.ProvisionRescatar(token);
        }
        
        public System.Threading.Tasks.Task<CapaObjeto.ContenedorProvisiones> ProvisionRescatarAsync(string token) {
            return base.Channel.ProvisionRescatarAsync(token);
        }
    }
}
